<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Description>Tedd.Quicly.Client</Description>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Tedd.Quicly.Core\Tedd.Quicly.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="Tedd.Quicly.Client.Tests" />
  </ItemGroup>
</Project>
