<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Description>Tedd.Quicly.Server</Description>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Tedd.Quicly.Core\Tedd.Quicly.Core.csproj" />
    <ProjectReference Include="..\Tedd.Quicly.Http\Tedd.Quicly.Http.csproj" />
    <ProjectReference Include="..\Tedd.Quicly.Acme\Tedd.Quicly.Acme.csproj" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="Tedd.Quicly.Server.Tests" />
  </ItemGroup>
</Project>
