using System.Globalization;
using System.Text;

namespace Tedd.Quicly.Http3.Tests.Generation;

/// <summary>
/// One-off generator for the Huffman code table and the QPACK static table. It reads
/// <c>docs/reference/h3_tables.txt</c>, renders the C# sources and asserts that the committed files match
/// (so the tables can never drift from the reference data). Set the environment variable
/// <c>TEDD_QUICLY_REGENERATE_TABLES=1</c> to (re)write the files instead of comparing.
/// </summary>
public class TableGenerator
{
    private const string RegenerateVariable = "TEDD_QUICLY_REGENERATE_TABLES";

    private static readonly string[] s_outputs =
    [
        "src/Tedd.Quicly.Http3/Qpack/HuffmanTable.Generated.cs",
        "src/Tedd.Quicly.Http3/Qpack/QpackStaticTableData.Generated.cs",
        "benchmarks/Tedd.Quicly.Archive/Http3/HuffmanTableV0.Generated.cs",
    ];

    [Fact]
    public void Generated_Tables_Match_Reference_Data()
    {
        string root = FindRepositoryRoot();
        string reference = File.ReadAllText(Path.Combine(root, "docs", "reference", "h3_tables.txt"));
        ParseReference(reference, out var staticEntries, out var codes, out var lengths);

        Assert.Equal(99, staticEntries.Count);
        Assert.Equal(257, codes.Length);

        string[] rendered =
        [
            RenderHuffmanTable(codes, lengths, "Tedd.Quicly.Http3.Qpack", "HuffmanTable"),
            RenderStaticTable(staticEntries),
            RenderHuffmanTable(codes, lengths, "Tedd.Quicly.Archive.Http3", "HuffmanTableV0"),
        ];

        bool regenerate = Environment.GetEnvironmentVariable(RegenerateVariable) == "1";
        for (int i = 0; i < s_outputs.Length; i++)
        {
            string path = Path.Combine(root, s_outputs[i]);
            if (regenerate)
            {
                Directory.CreateDirectory(Path.GetDirectoryName(path)!);
                File.WriteAllText(path, rendered[i].Replace("\n", "\r\n", StringComparison.Ordinal), new UTF8Encoding(false));
            }
            else
            {
                Assert.True(File.Exists(path), $"Missing generated file {path}; run with {RegenerateVariable}=1");
                string actual = File.ReadAllText(path).Replace("\r\n", "\n", StringComparison.Ordinal);
                Assert.Equal(rendered[i], actual);
            }
        }
    }

    internal static string FindRepositoryRoot()
    {
        string? dir = AppContext.BaseDirectory;
        while (dir is not null)
        {
            if (File.Exists(Path.Combine(dir, "Tedd.Quicly.slnx"))) return dir;
            dir = Path.GetDirectoryName(dir);
        }
        throw new InvalidOperationException("Repository root (Tedd.Quicly.slnx) not found above " + AppContext.BaseDirectory);
    }

    internal static void ParseReference(string text, out List<(int Index, string Name, string Value)> staticEntries, out uint[] codes, out byte[] lengths)
    {
        staticEntries = [];
        codes = new uint[257];
        lengths = new byte[257];
        int section = 0;
        foreach (string rawLine in text.Split('\n'))
        {
            string line = rawLine.TrimEnd('\r');
            if (line.Length == 0) continue;
            if (line == "QPACK_STATIC") { section = 1; continue; }
            if (line == "HUFFMAN") { section = 2; continue; }
            if (section == 1)
            {
                string[] parts = line.Split('\t');
                Assert.True(parts.Length is 2 or 3, "bad static table line: " + line);
                staticEntries.Add((int.Parse(parts[0], CultureInfo.InvariantCulture), parts[1], parts.Length == 3 ? parts[2] : string.Empty));
            }
            else if (section == 2)
            {
                string[] parts = line.Split(' ');
                Assert.Equal(3, parts.Length);
                int symbol = int.Parse(parts[0], CultureInfo.InvariantCulture);
                uint code = uint.Parse(parts[1].AsSpan(2), NumberStyles.HexNumber, CultureInfo.InvariantCulture);
                byte len = byte.Parse(parts[2], CultureInfo.InvariantCulture);
                codes[symbol] = code;
                lengths[symbol] = len;
            }
        }
        for (int i = 0; i < staticEntries.Count; i++) Assert.Equal(i, staticEntries[i].Index);
    }

    private static string Header(string section) =>
        "// <auto-generated>\n" +
        $"// Generated from docs/reference/h3_tables.txt ({section} section) by\n" +
        "// tests/Tedd.Quicly.Http3.Tests/Generation/TableGenerator.cs. Regenerate with:\n" +
        "//   TEDD_QUICLY_REGENERATE_TABLES=1 dotnet test tests/Tedd.Quicly.Http3.Tests -c Release\n" +
        "// Do not edit by hand.\n" +
        "// </auto-generated>\n\n";

    internal static string RenderHuffmanTable(uint[] codes, byte[] lengths, string ns, string className)
    {
        var sb = new StringBuilder();
        sb.Append(Header("HUFFMAN"));
        sb.Append("namespace ").Append(ns).Append(";\n\n");
        sb.Append("/// <summary>HPACK/QPACK Huffman code table (RFC 7541 Appendix B). Index = symbol; 256 = EOS.</summary>\n");
        sb.Append("internal static class ").Append(className).Append("\n{\n");
        sb.Append("    /// <summary>Number of symbols including EOS.</summary>\n");
        sb.Append("    public const int SymbolCount = 257;\n\n");
        sb.Append("    /// <summary>The end-of-string symbol.</summary>\n");
        sb.Append("    public const int Eos = 256;\n\n");
        sb.Append("    /// <summary>Codes, left-aligned in 32 bits.</summary>\n");
        sb.Append("    public static ReadOnlySpan<uint> Codes => s_codes;\n\n");
        sb.Append("    // Held in a static array rather than written inline as `ReadOnlySpan<uint> Codes => [...]`. For element\n");
        sb.Append("    // types wider than a byte the compiler lowers that form to RuntimeHelpers.CreateSpan<T>, whose ldtoken of\n");
        sb.Append("    // the data field allocates a 72-byte field handle on every call until the JIT folds the intrinsic away at\n");
        sb.Append("    // tier 1 - so unoptimised and tier-0 code allocates once per Encode, on the QPACK hot path. Lengths below\n");
        sb.Append("    // is a byte span, which lowers to a plain data-field address and never allocates, so it stays inline.\n");
        sb.Append("    private static readonly uint[] s_codes =\n    [\n");
        for (int i = 0; i < codes.Length; i++)
        {
            if (i % 8 == 0) sb.Append("        ");
            sb.Append("0x").Append(codes[i].ToString("X8", CultureInfo.InvariantCulture)).Append(',');
            sb.Append(i % 8 == 7 || i == codes.Length - 1 ? "\n" : " ");
        }
        sb.Append("    ];\n\n");
        sb.Append("    /// <summary>Code lengths in bits.</summary>\n");
        sb.Append("    public static ReadOnlySpan<byte> Lengths =>\n    [\n");
        for (int i = 0; i < lengths.Length; i++)
        {
            if (i % 16 == 0) sb.Append("        ");
            sb.Append(lengths[i].ToString(CultureInfo.InvariantCulture)).Append(',');
            sb.Append(i % 16 == 15 || i == lengths.Length - 1 ? "\n" : " ");
        }
        sb.Append("    ];\n}\n");
        return sb.ToString();
    }

    internal static string RenderStaticTable(List<(int Index, string Name, string Value)> entries)
    {
        var blob = new List<byte>();
        var layout = new List<ushort>();
        foreach (var e in entries)
        {
            byte[] name = Encoding.UTF8.GetBytes(e.Name);
            byte[] value = Encoding.UTF8.GetBytes(e.Value);
            layout.Add((ushort)blob.Count);
            layout.Add((ushort)name.Length);
            blob.AddRange(name);
            layout.Add((ushort)blob.Count);
            layout.Add((ushort)value.Length);
            blob.AddRange(value);
        }

        var sb = new StringBuilder();
        sb.Append(Header("QPACK_STATIC"));
        sb.Append("namespace Tedd.Quicly.Http3.Qpack;\n\n");
        sb.Append("/// <summary>QPACK static table (RFC 9204 Appendix A) as one contiguous byte blob plus a layout array.</summary>\n");
        sb.Append("internal static class QpackStaticTableData\n{\n");
        sb.Append("    /// <summary>Number of entries.</summary>\n");
        sb.Append("    public const int EntryCount = ").Append(entries.Count.ToString(CultureInfo.InvariantCulture)).Append(";\n\n");
        sb.Append("    /// <summary>Per entry: nameOffset, nameLength, valueOffset, valueLength (offsets into <see cref=\"Blob\"/>).</summary>\n");
        sb.Append("    public static ReadOnlySpan<ushort> Layout => s_layout;\n\n");
        sb.Append("    // Held in a static array for the reason given in HuffmanTable: a `ReadOnlySpan<ushort> => [...]` property\n");
        sb.Append("    // lowers to RuntimeHelpers.CreateSpan<ushort>, whose ldtoken allocates 72 bytes per call until the JIT\n");
        sb.Append("    // optimises it away, and every field line encoded or decoded reads this table at least once. Blob below is\n");
        sb.Append("    // a byte span, which lowers to a data-field address and never allocates, so it stays inline.\n");
        sb.Append("    private static readonly ushort[] s_layout =\n    [\n");
        for (int i = 0; i < entries.Count; i++)
        {
            sb.Append("        ");
            for (int j = 0; j < 4; j++)
            {
                sb.Append(layout[i * 4 + j].ToString(CultureInfo.InvariantCulture)).Append(',');
                if (j < 3) sb.Append(' ');
            }
            sb.Append(" // ").Append(i.ToString(CultureInfo.InvariantCulture)).Append(": ").Append(entries[i].Name);
            if (entries[i].Value.Length != 0) sb.Append(" = ").Append(entries[i].Value);
            sb.Append('\n');
        }
        sb.Append("    ];\n\n");
        sb.Append("    /// <summary>All names and values concatenated (UTF-8).</summary>\n");
        sb.Append("    public static ReadOnlySpan<byte> Blob =>\n    [\n");
        for (int i = 0; i < blob.Count; i++)
        {
            if (i % 16 == 0) sb.Append("        ");
            sb.Append("0x").Append(blob[i].ToString("X2", CultureInfo.InvariantCulture)).Append(',');
            sb.Append(i % 16 == 15 || i == blob.Count - 1 ? "\n" : " ");
        }
        sb.Append("    ];\n}\n");
        return sb.ToString();
    }
}
