<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Description>Tedd.Quicly.Transport.MsQuic</Description>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Tedd.Quicly.Core\Tedd.Quicly.Core.csproj" />
    <ProjectReference Include="..\Tedd.Quicly.Http3\Tedd.Quicly.Http3.csproj" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="Tedd.Quicly.Transport.MsQuic.Tests" />
  </ItemGroup>
</Project>
